Inject Language specific run files
- Updated scripts: Return non-zero exit code if program is not found.
  Give better feedback to user if a file is missing.
- Updated tests
- Added datamodels and logic
- Add new field to submission form

diff --git a/lib/run_scripts/c b/lib/run_scripts/c
--- a/lib/run_scripts/c
+++ b/lib/run_scripts/c
@@ -1,7 +1,7 @@
 #!/bin/sh
 if [ ! -f program.c ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.c' not found. Did you add this to your submission?"
+    exit 1
 fi
 gcc program.c -o program
 ./program
diff --git a/lib/run_scripts/cplus b/lib/run_scripts/cplus
--- a/lib/run_scripts/cplus
+++ b/lib/run_scripts/cplus
@@ -1,7 +1,7 @@
 #!/bin/sh
 if [ ! -f program.cpp ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.cpp' not found. Did you add this to your submission?"
+    exit 1
 fi
 g++ program.cpp -o program
 ./program
diff --git a/lib/run_scripts/java b/lib/run_scripts/java
--- a/lib/run_scripts/java
+++ b/lib/run_scripts/java
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ ! -f program.jar ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.jar' not found. Did you add this to your submission?"
+    exit 1
 fi
 java -jar program.jar
diff --git a/lib/run_scripts/javascript b/lib/run_scripts/javascript
--- a/lib/run_scripts/javascript
+++ b/lib/run_scripts/javascript
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ ! -f program.js ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.js' not found. Did you add this to your submission?"
+    exit 1
 fi
 node program.js
diff --git a/lib/run_scripts/python b/lib/run_scripts/python
--- a/lib/run_scripts/python
+++ b/lib/run_scripts/python
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ ! -f program.py ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.py' not found. Did you add this to your submission?"
+    exit 1
 fi
 python3 program.py
diff --git a/lib/run_scripts/ruby b/lib/run_scripts/ruby
--- a/lib/run_scripts/ruby
+++ b/lib/run_scripts/ruby
@@ -1,6 +1,6 @@
 #!/bin/sh
 if [ ! -f program.rb ]; then
-    echo "Program file not found!"
-    exit
+    echo "Program file 'program.rb' not found. Did you add this to your submission?"
+    exit 1
 fi
 ruby program.rb
